### ISSUE TITLE
Need a non-normative example showing how the AS extends the spec to make it all work

### ISSUE THREAD

**Issue by gffletch** [aaronpk/oauth-first-party-native-apps#14]
I think we will need more clarity on how an AS can leverage this spec to produce a fully working flow. There are statements like... "the AS MAY define additional parameters" but the reality is the AS MUST define additional parameters to make a concrete flow work. In that sense I think we need to make that more clear.

**Comment by aaronpk** [comment]
I think this might be covered by the examples created for #15
