### ISSUE TITLE
Include non-normative examples in the Appendix

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-native-apps#15]
e.g. use of login identifier (such as e-mail), that theAS can then use to do realm discovery (find the right IdP).

**Comment by aaronpk** [comment]
We can pull from the list of examples on the older draft:

https://github.com/aaronpk/oauth-direct-interaction-grant/blob/main/draft-parecki-oauth-direct-interaction-grant.md#use-cases
