### ISSUE TITLE
Response Mode

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-native-apps#2]
What profiling would we need to make to ensure that the new endpoint accepts any parameter the authorization end-point. The goal is to allow layering and use of other OAuth capabilities. Do we borrow from PAR?

**Comment by aaronpk** [comment]
Language from PAR:

> The endpoint accepts the authorization request parameters defined in [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)] for the authorization endpoint as well as all applicable extensions defined for the authorization endpoint.

George: Some parameters have meaning in a web context but don't have meaning in a native mechanism (e.g. response_mode=query). It is out of scope as to what the AS does in the case that an extension defines a parameter that is invalid in this use case.
