### ISSUE TITLE
OIDC compatibility

### ISSUE THREAD

**Issue by PieterKas** [aaronpk/oauth-first-party-native-apps#3]
Would we need a second profile to use this with OpenID Connect? How do we expect an AS that supports both OAuth and OIDC to implement this endpoint.

Aaron - make sure this is possible without breaking anything.

George - provide some guidance on what behaviour we want. Get AS behaviour consistent to simplify native implementations (no AS specific code needed). One idea - use examples from OIDC in a non-normative way.

OmniAuth - maintains a list of providers their library supports. 

Aaron- 2 classes of implementors. (1) proprietary (2) those using OIDC

**Comment by aaronpk** [comment]
Copy language from PAR:

> Some examples of such extensions include Proof Key for Code Exchange (PKCE) [[RFC7636](https://datatracker.ietf.org/doc/html/rfc7636)], Resource Indicators [[RFC8707](https://datatracker.ietf.org/doc/html/rfc8707)], and OpenID Connect (OIDC) [[OIDC](http://openid.net/specs/openid-connect-core-1_0.html)].
